- hosts: localhost
  vars:
    bin_path: "~/.local/bin"
    config_path: "~/.config"
    pip_packages:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
    docker-packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - gnupg2  # login without x11: https://stackoverflow.com/a/57485107
      - pass  # login without x11: https://stackoverflow.com/a/57485107
    user_packages:
      - rsync
      - sshpass  # ansible login with password
      - git
      - socat
      - python3-venv
      - trash-cli
      - ffmpeg
      - shellcheck  # ale
      - fzy
      - cargo  # rust
  tasks:
    - name: Install local & up-to-date pip
      command: python3 -m pip install --upgrade pip
    - name: Install pip packages
      pip:
        name:
          - PyYAML
          - ansible
          - ansible-lint  # ale
          - autopep8
          - cmake
          - cmake_format  # ale
          - cmakelint  # ale
          - conan
          - docker
          - docopt
          - gita
          - gitlint  # ale
          - pygit2
          - pylint  # ale
          - pynvim
          - python-apt
          - ranger-fm
          - requests
          - setuptools
          - speedtest-cli
          - trash-cli
          - virtualenv
          - yamllint  # ale
          - yapf  # ale
        extra_args: --user
    - name: Update system
      apt:
        state: latest
        update_cache: true
        autoremove: true
        upgrade: safe
      become: true
    - name: Install user utilities
      apt:
        pkg: "{{ user_packages }}"
        state: latest
        update_cache: true
      become: true
    - name: Update dotfiles
      shell:
        cmd: "cd ~ && curl -Ls 'https://github.com/nrobinaubertin/dotfiles/archive/master.tar.gz' | tar xz --strip 1"
    # modprobe fuse not needed: https://github.com/microsoft/WSL2-Linux-Kernel/issues/58
    - name: Fetch additional apps
      get_url:
        url: "{{ item.url }}"
        dest: "{{ bin_path }}/{{ item.dest }}"
        mode: 0755
      with_items:
        - url: "https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage"
          dest: "nvim"
        - url: "https://yt-dl.org/downloads/latest/youtube-dl"
          dest: "youtube-dl"
    - name: Fetch additional apps
      unarchive:
        src: "{{ item }}"
        dest: "{{ bin_path }}"
        mode: 0755
        remote_src: true
        extra_opts:
          - --strip-components=1
      with_items:
        - "https://github.com/FiloSottile/age/releases/download/v1.0.0-beta2/age-v1.0.0-beta2-linux-amd64.tar.gz"
    - name: Install cargo packages
      command: "cargo install {{ item }}"
      with_items:
        - bat
        - du-dust
        - exa
        - fd-find
        - ripgrep
        - tokei
        - rage
